
post http://localhost:4000/user
Content-Type: application/json

{
    "username": "soupmonsterr",
    "email": "gggggg@gmi.com",
    "password": "password12"
}


###


post http://localhost:4000/user/login
Content-Type: application/json

{
    "email": "gggg@gmi.com",
    "password": "password12"
}

###

get http://localhost:4000/user/botfile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdnZ2dAZ21pLmNvbSIsInVzZXJuYW1lIjoic291cG1vbnN0ZXJyIiwiaWF0IjoxNjU2MzI1MjQ4LCJleHAiOjE2NTYzMjUyNzh9.45A2v1z72D4_OGBbxDIepxfg70Waopwq7qZJ-Kr-lh0

###

post http://localhost:4000/user/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdnZ2dAZ21pLmNvbSIsInVzZXJuYW1lIjoic291cG1vbnN0ZXJyIiwiaWF0IjoxNjU2MzI0NDk3fQ.WFfMGp6QvQffRSzXKqg6Epl5Pz_yJ5xdjfSwq7Hk50o"
}